### ISSUE TITLE
Making a bunch of lines to get the y scrollbar and then inserting a ton to get the left scrollbar freezes the app

### ISSUE THREAD

**Issue by Moosems** [littlewhitecloud/TkTerminal#22]

**Comment by littlewhitecloud** [comment]
Can you give a screenshot?
I tested it but it still working

**Comment by Moosems** [comment]
Yes, I can.

**Comment by littlewhitecloud** [comment]
So it only happened when warp = “none”?

**Comment by Moosems** [comment]
Yea. Wrap=none.

**Comment by littlewhitecloud** [comment]
Fine, I think we had fixed it so I will close it...

**Comment by littlewhitecloud** [comment]
I think it is about python’s performance

**Comment by littlewhitecloud** [comment]
I think it is about python’s speed.

**Comment by Moosems** [comment]
I don't think so. Doesn't happen elsewhere. Either an issue with the scroll bars or with the key press bind.

**Comment by littlewhitecloud** [comment]
Can you use the code in fix branch and set ```warp="none"``` to test it? I did some small changes.

**Comment by littlewhitecloud** [comment]
Will it still happened on fix branch? If not I will append it to the fix pr’s fix list.

**Comment by littlewhitecloud** [comment]
So, what's the result of using the latest code to test it?

**Comment by Moosems** [comment]
I'm actually editing on my phone right now and haven't been able to test it 😅.

**Comment by littlewhitecloud** [comment]
> I'm actually editing on my phone right now and haven't been able to test it 😅.

Wow! I often edit the code on my ipad!

**Comment by littlewhitecloud** [comment]
Can you write down some steps to reduce it (more details)?

**Comment by littlewhitecloud** [comment]
![image](https://github.com/littlewhitecloud/TkTerminal/assets/71159641/f1d681c2-0c36-48a3-8eaa-4a25f66eea50)
It didn't happen on my computer

**Comment by littlewhitecloud** [comment]
I tried input a lot of but it didn't freeze

**Comment by littlewhitecloud** [comment]
maybe macos only?
