### ISSUE TITLE
A scrollbar may useless when ```warp="char"``` ```warp="word"```

### ISSUE THREAD

**Issue by littlewhitecloud** [littlewhitecloud/TkTerminal#40]
![image](https://github.com/littlewhitecloud/TkTerminal/assets/71159641/0895713a-a4cf-4015-9e43-7d9dacacb707)

**Comment by Moosems** [comment]
On the PR?

**Comment by littlewhitecloud** [comment]
> On the PR?

yes

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud I'm going to make a to-do list of all the stuff to complete in the PR and then make a separate one in my style to accomplish these. Would you make a list of things you'd like me to do?

What’s your style?
Can you edit it by yourself?

**Comment by littlewhitecloud** [comment]
You can choose some issues that you’d like to fix~ But issues in #32 need to fix, maybe you can see the fix list in the pr.

**Comment by littlewhitecloud** [comment]
by the way, can you open an issues to report the bug in #35 the fixed #19 code still have bug

**Comment by littlewhitecloud** [comment]
> #22 and #16 both break still and #19 has issues.

Can you open a issues to describe the bug?

**Comment by Moosems** [comment]
I can explain 19 better but the other two haven't changed at all. Communicate() is actually just to allow input.

**Comment by littlewhitecloud** [comment]
> I can explain 19 better but the other two haven't changed at all. Communicate() is actually just to allow input.

So can you open an issues to explain 19?

**Comment by Moosems** [comment]
I'll just expand in the current issue.
